### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by SebCanet** [ajoino/pyrrowhead#2]
Hi,
when looking for documentation, the "Read the docs" web site answers: "Project marked as spam".
Is there any documentation somewhere else?
Thanks.

**Comment by ajoino** [comment]
Seems like readthedocs has marked all my projects as spam, I opened a ticket with them and will hopefully get a response soon.

**Comment by ajoino** [comment]
@SebCanet They have unmarked the projects, the documentation in the links should work now.

Closing the issue for now, feel free to reopen if issues remain.
